

name: dev_build

on: 
    workflow_dispatch:

env:
     SCRIBE_URL: "https://api.dev.hub.scribesecurity.com/scribe-proxy"
     SCRIBE_LOGIN_URL: "https://scribesec-dev.us.auth0.com"
     SCRIBE_AUDIENCE: "api.dev.scribesecurity.com"

jobs:

 scribe-report-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    
    
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

#       - uses: actions/checkout@v3
#         with:
#           repository: mongo-express/mongo-express
#           ref: refs/tags/v1.0.0-alpha.4
#           path: mongo-express-scm

#       - name: Scm generate bom, upload to scribe
#         id: valint_bom_scm
#         uses: scribe-security/action-bom@master
#         with:
#            type: dir
#            target: 'mongo-express-scm'
#            scribe-enable: true
#            product-key: "00_github_upload_build"
#            scribe-client-id: ${{ secrets.SCRIBE_DEV_M2M_CLIENT_ID }}
#            scribe-client-secret: ${{ secrets.SCRIBE_DEV_M2M_CLIENT_SECRET }}
#            scribe-url: "https://api.dev.hub.scribesecurity.com/scribe-proxy"
#            scribe-login-url: "https://scribesec-dev.us.auth0.com"
#            scribe-audience: "api.dev.scribesecurity.com"

      # Build and push your image - this example skips this step as we're using the published mongo express.

      - name: Image generate bom, upload to scribe
        id: valint_bom_image
        uses: scribe-security/action-bom@master
        with:
          type: docker # To be included only if you want to to use docker daemon to access the image (for example, creating your docker image locally)
          target: mysql:latest
          scribe-enable: true
          product-key: "00_github_upload_build"
          scribe-client-id: ${{ secrets.SCRIBE_DEV_M2M_CLIENT_ID }}
          scribe-client-secret: ${{ secrets.SCRIBE_DEV_M2M_CLIENT_SECRET }}
          scribe-url: "https://api.dev.hub.scribesecurity.com/scribe-proxy"
          scribe-login-url: "https://scribesec-dev.us.auth0.com"
          scribe-audience: "api.dev.scribesecurity.com"

      - uses: actions/upload-artifact@v2
        with:
          name: scribe-reports
          path: |
            ${{ steps.valint_bom_scm.outputs.OUTPUT_PATH }}
            ${{ steps.valint_bom_image.outputs.OUTPUT_PATH }}
      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate SLSA provenance statement
        id: valint_slsa_statement
        uses: scribe-security/action-bom@master
        with:
          target: mysql:latest
          format: statement-slsa
          product-key: "00_github_upload_build"

      - uses: actions/upload-artifact@v2
        with:
         name: provenance
         path: ${{ steps.valint_slsa_statement.outputs.OUTPUT_PATH }}


  
#   scribe-report-test:
#     runs-on: ubuntu-latest
#     permissions:
#       id-token: write
#     steps:
#       - name: create file and Docker
#         run: | 
#           echo `date` > tmp.txt
#           echo "FROM scratch" > Dockerfile
#           echo "COPY . ." >> Dockerfile
#           docker build -t date:latest .
 
#       - uses: actions/checkout@v3
      
#       - name: install opa
#         run: | 
#           curl -L -o opa https://openpolicyagent.org/downloads/v0.46.1/opa_linux_amd64_static
#           chmod +x ./opa
#           echo "installed"
#           whereis opa
#           ./opa version
      
      
#       - name: Clone GuillaumeFalourd/formulas-training PRIVATE repository
#         uses: GuillaumeFalourd/clone-github-repo-action@v2
#         with:
#             owner: 'scribe-security'
#             repository: 'GitHub-Posture'
#             access-token: ${{ secrets.GH_ACCESS_TOKEN }}
      
            
#       - name: Generate cyclonedx json SBOM
#         id: gensbom_json
#         uses: scribe-security/actions/gensbom/bom@master
#         with:
#           type: docker            
#           target: galaxy/gx-it-proxy:latest
# #           format: json
#           format: attest
# #           verbose: 2
# # #           force: true
#           scribe-enable: true
# #           product-key: ${{ secrets.SCRIBE_DEV_PRODUCT_KEY }}
#           product-key: "00_github_upload_build"
#           scribe-client-id: ${{ secrets.SCRIBE_DEV_M2M_CLIENT_ID }}
#           scribe-client-secret: ${{ secrets.SCRIBE_DEV_M2M_CLIENT_SECRET }}
# #           scribe-client-id: KPW7yHFizbDhIXlHA28hhUfaoliiPn9u
# #           scribe-client-secret: 36QnyovoREMnsNKJD9mEPJ9lfet44rM0NF18dPipSkfBCe09zP7aig8AtB80dIPK
#           scribe-url: "https://api.dev.hub.scribesecurity.com/scribe-proxy"
#           scribe-login-url: "https://scribesec-dev.us.auth0.com"
#           scribe-audience: "api.dev.scribesecurity.com"



#       - name: Generate slsa prov statement
#         id: gensbom_slsa
#         uses: scribe-security/actions/gensbom/bom@master
#         with:
#           type: docker
#           target: galaxy/gx-it-proxy:latest
# #           format: statement-slsa
# #           format: attest-slsa
# #           product-key: ${{ secrets.SCRIBE_DEV_PRODUCT_KEY }}
# #           product-key: sdfsdfsdfsdfsdf 
#           product-key: "00_github_upload_build"
#           verbose: 2
#           force: true
          
#       - name: generate slsa report
#         run: | # echo "SLSA is great" > slsa.json
#           cat input.json | sed "s/GH_TOKEN/${{ secrets.GH_ACCESS_TOKEN }}/" | ./opa eval -I --format=pretty -b GitHub-Posture/github data.github.slsa.report > slsa.json
#           cat slsa.json

#       - uses: actions/upload-artifact@v2
#         with:
#           name: provenance
#           path: ${{ steps.gensbom_slsa.outputs.OUTPUT_PATH }}
          
#       - uses: actions/upload-artifact@v2
#         with:
#           name: slsa_report
#           path: slsa.json 
          
#       - name: Cache input.json
#         uses: actions/cache@v3
#         with:
#          path: ~/cache.txt
#          key: my-key
          
 
       
          
 
       
