# This is a basic workflow to help you get started with Actions

name: simply-workflow

env:
     SCRIBE_URL: "https://api.dev.hub.scribesecurity.com/scribe-proxy"
     SCRIBE_LOGIN_URL: "https://scribesec-dev.us.auth0.com"
     SCRIBE_AUDIENCE: "api.dev.scribesecurity.com"


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

          
         
      - name: Scm generate bom, upload to scribe
        id: valint_bom_scm
        uses: scribe-security/action-bom@master
        with:
          type: dir
          target: .
          verbose: 2
          scribe-enable: true
          scribe-client-id: ${{ secrets.SCRIBE_DEV_M2M_CLIENT_ID }}
          scribe-client-secret: ${{ secrets.SCRIBE_DEV_M2M_CLIENT_SECRET }}
          scribe-url: "https://api.dev.hub.scribesecurity.com/scribe-proxy"
          scribe-login-url: "https://scribesec-dev.us.auth0.com"
          scribe-audience: "api.dev.scribesecurity.com"

          
      - name: Image generate bom, upload to scribe
        id: valint_bom_image
        uses: scribe-security/action-bom@master
        with:
          type: docker # To be included only if you want to to use docker daemon to access the image (for example, creating your docker image locally)
          target: .
          verbose: 2
          scribe-enable: true
          scribe-client-id: ${{ secrets.SCRIBE_DEV_M2M_CLIENT_ID }}
          scribe-client-secret: ${{ secrets.SCRIBE_DEV_M2M_CLIENT_SECRET }}
          scribe-url: "https://api.dev.hub.scribesecurity.com/scribe-proxy"
          scribe-login-url: "https://scribesec-dev.us.auth0.com"
          scribe-audience: "api.dev.scribesecurity.com"


